// Package charset patches Swedish glyph data into the classic SCUMM CHAR blocks
// embedded in MONKEY1.000/001 (the monkeycdalt game ID used by both the standalone
// Classic CD-ROM release and the Classic mode inside MI1SE).
//
// # CHAR blocks
//
// Monkey Island 1 (SCUMM v5) stores font bitmaps in CHAR blocks inside MONKEY1.001.
// Each CHAR block holds the pixel data for one character set. There are five blocks
// relevant to a Swedish translation:
//
//	CHAR_0001 — 10 px, general-purpose text (action descriptions, narrator lines)
//	CHAR_0002 — 12 px, colored dialog font  (NPC speech bubbles, conversation text)
//	CHAR_0003 —  8 px, small secondary font (miscellaneous small on-screen text)
//	CHAR_0004 — 18 px, verb button font     (Pick up, Look at, Talk to, etc.)
//	CHAR_0006 — 13 px, drop-shadow menu font (title screen and in-game menu)
//
// The English game ships with Latin glyphs only. Swedish characters (Å Ä Ö å ä ö é)
// are not present at the SCUMM codes used by the translation: codes 91–93 (replacing
// '[', '\', ']'), 123–125 (replacing '{', '|', '}'), and 130. Without patched CHAR
// blocks the game renders those codes as ASCII punctuation or nothing at all.
//
// # What was changed in each block
//
// The monkeycd_swe open-source project (https://github.com/jonte/monkeycd_swe) ships
// BMP exports of its Swedish-language CHAR blocks. Those BMPs contain Swedish glyphs
// at the correct code positions and were used as the source for our patches.
//
// For each block, the workflow was:
//  1. Export the English CHAR block from the SE's embedded MONKEY1.001 using scummrp.
//     The extracted blocks live in assets/charset/english/ and are committed to git.
//  2. Import the Swedish BMP (internal/charset/bitmaps/CHAR_NNNN_swedish.bmp) into a
//     copy of the English block using `scummfont i`. scummfont replaces glyph pixel
//     data in-place and updates the CHAR block's internal size fields automatically.
//  3. The patched block is written to internal/charset/gen/char_NNNN_patched.bin.
//     This file is generated by scripts/build.sh (Step 2) and is gitignored.
//
// To update a glyph: edit the BMP in internal/charset/bitmaps/, then re-run
// scripts/build.sh (which regenerates the .bin files as part of Step 2).
// To see the original English glyphs for reference, run
// scripts/extract_assets.sh — it exports the English CHAR blocks from the
// game to assets/charset/english_bitmaps/.
//
// # Runtime behaviour
//
// Patch() extracts the platform-appropriate scummrp binary to a temp directory,
// uses it to dump all CHAR blocks from the game directory, overwrites the five
// target blocks with the patched binaries, then uses scummrp to re-import them.
// scummrp handles all SCUMM block-level housekeeping: XOR encoding of MONKEY1.001,
// LFLF/LECF size fields, the LOFF room-offset table, and the DCHR charset directory.
package charset

import (
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

// Swedish-patched CHAR blocks, embedded at compile time.
// Generated by scripts/build.sh Step 2 into gen/ (gitignored).

//go:embed gen/char_0001_patched.bin
var patchedChar0001 []byte // 10 px general text

//go:embed gen/char_0002_patched.bin
var patchedChar0002 []byte // 12 px colored dialog (NPC speech)

//go:embed gen/char_0003_patched.bin
var patchedChar0003 []byte // 8 px small text

//go:embed gen/char_0004_patched.bin
var patchedChar0004 []byte // 18 px verb buttons

//go:embed gen/char_0006_patched.bin
var patchedChar0006 []byte // 13 px drop-shadow menu font

// scummrp binaries for each supported platform, embedded at compile time.
// scummrp is used to dump and re-import CHAR blocks without disturbing the
// surrounding MONKEY1.001 structure.

//go:embed assets/scummrp-linux-x64
var scummrpLinux []byte

//go:embed assets/scummrp-darwin-x64
var scummrpDarwin []byte

//go:embed assets/scummrp-windows-x64.exe
var scummrpWindows []byte

// Patch replaces CHAR_0001, CHAR_0002, CHAR_0003, CHAR_0004, and CHAR_0006 in the
// MONKEY1.000/001 files in gameDir with Swedish-glyph versions.
//
// gameDir must contain MONKEY1.000 and MONKEY1.001 in uppercase, as required
// by scummrp's monkeycdalt game ID. Both the Classic and SE pipelines copy the
// game files to a temp directory with uppercase names before calling Patch.
func Patch(gameDir string) error {
	var scummrpBin []byte
	var scummrpName string
	switch runtime.GOOS {
	case "linux":
		scummrpBin = scummrpLinux
		scummrpName = "scummrp"
	case "darwin":
		scummrpBin = scummrpDarwin
		scummrpName = "scummrp"
	case "windows":
		scummrpBin = scummrpWindows
		scummrpName = "scummrp.exe"
	default:
		return fmt.Errorf("unsupported platform: %s", runtime.GOOS)
	}

	tmpDir, err := os.MkdirTemp("", "scummrp-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	scummrpPath := filepath.Join(tmpDir, scummrpName)
	if err := os.WriteFile(scummrpPath, scummrpBin, 0755); err != nil {
		return err
	}

	dumpDir := filepath.Join(tmpDir, "dump")

	run := func(args ...string) error {
		cmd := exec.Command(scummrpPath, args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		return cmd.Run()
	}

	// Export all CHAR blocks from MONKEY1.001 into the dump directory.
	// scummrp decodes the XOR-encoded game file and reconstructs the block hierarchy.
	if err := run("-g", "monkeycdalt", "-p", gameDir, "-t", "CHAR", "-od", dumpDir); err != nil {
		return fmt.Errorf("scummrp export: %w", err)
	}

	// Overwrite the five CHAR blocks with their Swedish-patched versions.
	// CHAR_0005 does not exist in monkeycdalt — that slot is simply unused.
	charDir := filepath.Join(dumpDir, "DISK_0001", "LECF", "LFLF_0010")
	for _, patch := range []struct {
		name string
		data []byte
	}{
		{"CHAR_0001", patchedChar0001},
		{"CHAR_0002", patchedChar0002},
		{"CHAR_0003", patchedChar0003},
		{"CHAR_0004", patchedChar0004},
		{"CHAR_0006", patchedChar0006},
	} {
		if err := os.WriteFile(filepath.Join(charDir, patch.name), patch.data, 0644); err != nil {
			return fmt.Errorf("write %s: %w", patch.name, err)
		}
	}

	// Re-import the patched CHAR blocks back into MONKEY1.001.
	// scummrp re-encodes with XOR, recalculates LFLF/LECF sizes, updates the LOFF
	// room-offset table, and rebuilds the DCHR charset directory entry.
	if err := run("-g", "monkeycdalt", "-p", gameDir, "-t", "CHAR", "-id", dumpDir); err != nil {
		return fmt.Errorf("scummrp import: %w", err)
	}

	return nil
}
