//go:build !buildpatcher

package charset

// Stub variables — populated by charset_embed.go when built with -tags buildpatcher.
// Generated by scripts/build.sh; Patch() returns ErrCharDataNotBuilt if nil.
var (
	patchedChar0001 []byte
	patchedChar0002 []byte
	patchedChar0003 []byte
	patchedChar0004 []byte
	patchedChar0006 []byte
)
