//go:build buildpatcher

package charset

import _ "embed"

// Swedish-patched CHAR blocks, embedded at compile time.
// Generated by scripts/build.sh Step 2 into gen/ (gitignored).

//go:embed gen/char_0001_patched.bin
var patchedChar0001 []byte // 10 px general text

//go:embed gen/char_0002_patched.bin
var patchedChar0002 []byte // 12 px colored dialog (NPC speech)

//go:embed gen/char_0003_patched.bin
var patchedChar0003 []byte // 8 px small text

//go:embed gen/char_0004_patched.bin
var patchedChar0004 []byte // 18 px verb buttons

//go:embed gen/char_0006_patched.bin
var patchedChar0006 []byte // 13 px drop-shadow menu font

