package charset

// PatchVerbLayout repositions the nine verb action buttons in MONKEY1.001 to
// a layout better suited to the Swedish word lengths.
//
// # Verb button layout
//
// In SCUMM v5 each verb button is defined in script SCRP_0022 with both its
// action ID and its screen coordinates. Changing the coordinates moves the button
// to a different cell in the 3×3 grid — the action travels with it.
//
// Original English layout:
//
//	Left (x=0x16) | Middle (x=0x48) | Right (x=0x7C)
//	Give          | Pick up          | Use             ← Top    (y=0x9B)
//	Open          | Look at          | Push            ← Middle (y=0xAB)
//	Close         | Talk to          | Pull            ← Bottom (y=0xBB)
//
// Patched layout (Swedish — shorter words on the right):
//
//	Left (x=0x16) | Middle (x=0x48) | Right (x=0x7C)
//	Öppna         | Titta            | Ge              ← Top    (y=0x9B)
//	Stäng         | Tala             | Ta              ← Middle (y=0xAB)
//	Putta         | Använd           | Dra             ← Bottom (y=0xBB)
//
// # How the patch is applied
//
// The patched SCRP_0022 binary is generated at build time by scripts/build.sh
// (which calls tools/patch_verbs.py on the extracted SCRP_0022 from the game).
// At runtime PatchVerbLayout uses scummrp to:
//  1. Dump all SCRP blocks from the game directory.
//  2. Overwrite SCRP_0022 with the embedded patched version.
//  3. Reimport the SCRP blocks back into MONKEY1.001.

import (
	_ "embed"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
)

// patchedSCRP0022 is the verb-layout-patched SCRP_0022 block, embedded at compile time.
// Generated by scripts/build.sh (via tools/patch_verbs.py) into gen/ (gitignored).
//
//go:embed gen/scrp_0022_patched.bin
var patchedSCRP0022 []byte

// PatchVerbLayout patches verb button positions in the game files in gameDir.
// gameDir must contain MONKEY1.000 and MONKEY1.001 in uppercase.
func PatchVerbLayout(gameDir string) error {
	var scummrpBin []byte
	var scummrpName string
	switch runtime.GOOS {
	case "linux":
		scummrpBin = scummrpLinux
		scummrpName = "scummrp"
	case "darwin":
		scummrpBin = scummrpDarwin
		scummrpName = "scummrp"
	case "windows":
		scummrpBin = scummrpWindows
		scummrpName = "scummrp.exe"
	default:
		return fmt.Errorf("unsupported platform: %s", runtime.GOOS)
	}

	tmpDir, err := os.MkdirTemp("", "scummrp-verbs-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	scummrpPath := filepath.Join(tmpDir, scummrpName)
	if err := os.WriteFile(scummrpPath, scummrpBin, 0755); err != nil {
		return err
	}

	dumpDir := filepath.Join(tmpDir, "dump")

	run := func(args ...string) error {
		cmd := exec.Command(scummrpPath, args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		return cmd.Run()
	}

	// Dump all SCRP blocks from MONKEY1.001.
	if err := run("-g", "monkeycdalt", "-p", gameDir, "-t", "SCRP", "-od", dumpDir); err != nil {
		return fmt.Errorf("scummrp export SCRP: %w", err)
	}

	// Locate SCRP_0022 in the dump — path differs between game variants.
	scrpPath, err := findFileInTree(dumpDir, "SCRP_0022")
	if err != nil {
		return fmt.Errorf("SCRP_0022 not found in scummrp dump: %w", err)
	}

	// Overwrite with the pre-patched verb layout.
	if err := os.WriteFile(scrpPath, patchedSCRP0022, 0644); err != nil {
		return fmt.Errorf("write SCRP_0022: %w", err)
	}

	// Reimport the patched SCRP blocks back into MONKEY1.001.
	if err := run("-g", "monkeycdalt", "-p", gameDir, "-t", "SCRP", "-id", dumpDir); err != nil {
		return fmt.Errorf("scummrp import SCRP: %w", err)
	}

	return nil
}

// findFileInTree walks root and returns the path of the first file named target.
func findFileInTree(root, target string) (string, error) {
	var found string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && d.Name() == target {
			found = path
			return fs.SkipAll
		}
		return nil
	})
	if err != nil {
		return "", err
	}
	if found == "" {
		return "", fmt.Errorf("%s not found under %s", target, root)
	}
	return found, nil
}
